redisHost: 127.0.0.1
kafkaConfiguration:
  producer:
    bootstrap.servers: 127.0.0.1:9092
    metadata.broker.list: 127.0.0.1:9092
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.type: sync

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
logging:
  level: INFO
  appenders:
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout
      - type: file
        currentLogFilename: /tmp/medi.log
        threshold: INFO
        archive: true
        archivedLogFilenamePattern: /tmp/medi-%d.log
        archivedFileCount: 5
        timeZone: UTC